[package]
name = "ruin-this"
version = "0.1.0"
authors = ["Dilyan Damyanov <dilyand@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
